# Documentation generator based on MkDocs
# Automatically documents API references
# References:
#   https://www.mkdocs.org/
#   https://mkdocstrings.github.io/recipes/

site_name: CALYPR
site_url: https://calypr.org

plugins:
  - search
  - macros
  - awesome-nav
  - open-in-new-tab # automatically open ext links in new tab

theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
  features:
    - navigation.indexes 
    # - navigation.footer
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  **/_*.md

nav:
  - Home: index.md
  - CALYPR Platform:
    - Quick Start: calypr/quick-start.md
    - Overview: calypr/index.md
    - Data Model & Metadata:
      - Introduction: calypr/data-model/introduction.md
      - FHIR Schema: calypr/data-management/meta-data.md
      - Integration (ETL): calypr/data-model/integration.md
    - Analysis:
      - calypr/analysis/query.md
    - Web Portal:
      - calypr/website/portal-explore.md
      - calypr/website/portal-download.md
    - Troubleshooting: calypr/troubleshooting.md
  - Tools:
    - tools/index.md
    - Git-DRS:
      - tools/git-drs/index.md
      - Getting Started:
        - tools/git-drs/installation.md
        - tools/git-drs/getting-started.md
      - User Guide:
        - tools/git-drs/adding-s3-files.md
        - tools/git-drs/remove-files.md
        - tools/git-drs/commands.md
      - Development:
        - tools/git-drs/developer-guide.md
        - tools/git-drs/troubleshooting.md
    - Forge:
      - tools/forge/index.md
    - Funnel:
      - tools/funnel/index.md
      - Getting Started:
        - tools/funnel/download.md
      - Documentation:
        - tools/funnel/docs.md
        - tasks.md
        - tools/funnel/docs/storage.md
        - tools/funnel/docs/compute.md
        - tools/funnel/docs/databases.md
        - tools/funnel/docs/security.md
        - tools/funnel/docs/metrics.md
        - tools/funnel/docs/events.md
        - tools/funnel/docs/development.md
    - GRIP:
      - tools/grip/index.md
      - Getting Started:
        - tools/grip/databases.md
        - tools/grip/clients.md
      - Commands:
        - tools/grip/commands.md
        - tools/grip/commands/create.md
        - tools/grip/commands/delete.md
        - tools/grip/commands/list.md
        - tools/grip/commands/query.md
        - tools/grip/commands/server.md
      - Queries:
        - tools/grip/queries.md
        - tools/grip/queries/aggregation.md
        - tools/grip/queries/filtering.md
        - tools/grip/queries/iterations.md
        - tools/grip/queries/jsonpath.md
        - tools/grip/queries/output.md
        - tools/grip/queries/record_transforms.md
        - tools/grip/queries/traversal_start.md
        - tools/grip/queries/traverse_graph.md
        - tools/grip/queries/jobs.md
      - GraphQL:
        - tools/grip/graphql.md
        - tools/grip/graphql/graph_schemas.md
        - tools/grip/graphql/graphql.md
      - Tutorials:
        - tools/grip/tutorials.md
        - tools/grip/tutorials/amazon.md
        - tools/grip/tutorials/pathway-commons.md
        - tools/grip/tutorials/tcga-rna.md
      - Development:
        - tools/grip/developers.md
        - tools/grip/gripper.md
        - tools/grip/gripper/proxy.md
        - tools/grip/jobs_api.md
        - tools/grip/security.md
  - Workflows:
    - workflows/upload.md
    - workflows/restrict-access.md
  - Administration:
    - Data Client:
      - tools/data-client/index.md
      - tools/data-client/authentication.md
      - tools/data-client/data_management.md
      - tools/data-client/access_requests.md
